#!/usr/bin/env node
/**
 * Build original payload-v2 into dist/payload.js (IIFE).
 * Does not read engine/ or dom/ from upstream trees.
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '..');
const SRC = path.join(__dirname, 'src');
const MARKER = 'claude-official-rtl-payload-v2';

function read(name) {
  return fs.readFileSync(path.join(SRC, name), 'utf8');
}

function stripModule(src) {
  const cut = src.indexOf('// __EXPORTS__');
  if (cut !== -1) src = src.slice(0, cut);
  return src
    .split('\n')
    .filter((line) => {
      const t = line.trim();
      if (t === "'use strict';" || t === '"use strict";') return false;
      if (t.includes('require(')) return false;
      if (t.startsWith('module.exports')) return false;
      return true;
    })
    .join('\n')
    .trim();
}

function buildPayload() {
  const detect = stripModule(read('detect.js'));
  const surfaces = stripModule(read('surfaces.js'));
  const cssMod = stripModule(read('css.js'));
  const apply = stripModule(read('apply.js'));

  // Wire modules onto a local namespace, then boot.
  return (
    `;(function () {\n` +
    `'use strict';\n` +
    `/* ${MARKER} — original layout-only engine; generated by payload-v2/build.mjs */\n` +
    `if (typeof document === 'undefined' || !document.documentElement) return;\n` +
    `var __ORTL = {};\n` +
    `// ---- detect ----\n` +
    detect +
    `\n__ORTL.detect = { isRtlCodePoint: isRtlCodePoint, isLtrLetterCodePoint: isLtrLetterCodePoint, countStrong: countStrong, firstStrongDir: firstStrongDir, detectBlockDir: detectBlockDir, plaintextOverrideDir: plaintextOverrideDir, resolvedDir: resolvedDir };\n` +
    `// ---- surfaces ----\n` +
    surfaces +
    `\n__ORTL.surfaces = { SELECTORS: SELECTORS, isEditableHost: isEditableHost, isXtermSurface: isXtermSurface, isCodeSurface: isCodeSurface, isNoTouch: isNoTouch, getScanRoots: getScanRoots, closestMatch: closestMatch };\n` +
    `// ---- css ----\n` +
    cssMod +
    `\n__ORTL.cssText = APPLY_CSS;\n` +
    `// ---- apply ----\n` +
    apply +
    `\n__ORTL.apply = { STAMP: STAMP, STAMP_DIR: STAMP_DIR, ROOT_ATTR: ROOT_ATTR, STYLE_ID: STYLE_ID, PAYLOAD_NAME: PAYLOAD_NAME, installStyles: installStyles, processRoot: processRoot, createController: createController, processProseLeaf: processProseLeaf, processListOrQuote: processListOrQuote, processTable: processTable, processInputChrome: processInputChrome };\n` +
    `// ---- boot ----\n` +
    `try {\n` +
    `  if (globalThis.__CLAUDE_OFFICIAL_RTL_V2__ && typeof globalThis.__CLAUDE_OFFICIAL_RTL_V2__.dispose === 'function') {\n` +
    `    globalThis.__CLAUDE_OFFICIAL_RTL_V2__.dispose();\n` +
    `  }\n` +
    `} catch (e) {}\n` +
    `var controller = createController(document, { detect: __ORTL.detect, surfaces: __ORTL.surfaces, cssText: __ORTL.cssText });\n` +
    `controller.start();\n` +
    `globalThis.__CLAUDE_OFFICIAL_RTL_V2__ = controller;\n` +
    `})();\n`
  );
}

function writeDist() {
  const payload = buildPayload();
  const distDir = path.join(ROOT, 'dist');
  fs.mkdirSync(distDir, { recursive: true });
  const out = path.join(distDir, 'payload.js');
  fs.writeFileSync(out, payload);
  // optional mirror for tooling
  fs.writeFileSync(path.join(distDir, 'payload-v2.js'), payload);
  return { out, bytes: Buffer.byteLength(payload), marker: MARKER };
}

const result = writeDist();
console.log(`payload-v2 built → ${result.out} (${result.bytes} bytes) [${result.marker}]`);
